development:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
  dir: scripts/migrations
  table: gorp_migrations

production:
  dialect: postgres
  datasource: host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=require
  dir: scripts/migrations
  table: gorp_migrations