// Code generated by protoc-gen-go. DO NOT EDIT.
// source: town.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Town struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TownCode             string   `protobuf:"bytes,2,opt,name=town_code,json=townCode,proto3" json:"town_code,omitempty"`
	TownName             string   `protobuf:"bytes,3,opt,name=town_name,json=townName,proto3" json:"town_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Town) Reset()         { *m = Town{} }
func (m *Town) String() string { return proto.CompactTextString(m) }
func (*Town) ProtoMessage()    {}
func (*Town) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{0}
}
func (m *Town) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Town.Unmarshal(m, b)
}
func (m *Town) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Town.Marshal(b, m, deterministic)
}
func (dst *Town) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Town.Merge(dst, src)
}
func (m *Town) XXX_Size() int {
	return xxx_messageInfo_Town.Size(m)
}
func (m *Town) XXX_DiscardUnknown() {
	xxx_messageInfo_Town.DiscardUnknown(m)
}

var xxx_messageInfo_Town proto.InternalMessageInfo

func (m *Town) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Town) GetTownCode() string {
	if m != nil {
		return m.TownCode
	}
	return ""
}

func (m *Town) GetTownName() string {
	if m != nil {
		return m.TownName
	}
	return ""
}

type TownList struct {
	Lists                []*Town  `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TownList) Reset()         { *m = TownList{} }
func (m *TownList) String() string { return proto.CompactTextString(m) }
func (*TownList) ProtoMessage()    {}
func (*TownList) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{1}
}
func (m *TownList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TownList.Unmarshal(m, b)
}
func (m *TownList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TownList.Marshal(b, m, deterministic)
}
func (dst *TownList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TownList.Merge(dst, src)
}
func (m *TownList) XXX_Size() int {
	return xxx_messageInfo_TownList.Size(m)
}
func (m *TownList) XXX_DiscardUnknown() {
	xxx_messageInfo_TownList.DiscardUnknown(m)
}

var xxx_messageInfo_TownList proto.InternalMessageInfo

func (m *TownList) GetLists() []*Town {
	if m != nil {
		return m.Lists
	}
	return nil
}

type GetTown struct {
	TownCode             string   `protobuf:"bytes,1,opt,name=town_code,json=townCode,proto3" json:"town_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTown) Reset()         { *m = GetTown{} }
func (m *GetTown) String() string { return proto.CompactTextString(m) }
func (*GetTown) ProtoMessage()    {}
func (*GetTown) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{2}
}
func (m *GetTown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTown.Unmarshal(m, b)
}
func (m *GetTown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTown.Marshal(b, m, deterministic)
}
func (dst *GetTown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTown.Merge(dst, src)
}
func (m *GetTown) XXX_Size() int {
	return xxx_messageInfo_GetTown.Size(m)
}
func (m *GetTown) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTown.DiscardUnknown(m)
}

var xxx_messageInfo_GetTown proto.InternalMessageInfo

func (m *GetTown) GetTownCode() string {
	if m != nil {
		return m.TownCode
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetTownSlot struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TownCode             string   `protobuf:"bytes,2,opt,name=town_code,json=townCode,proto3" json:"town_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTownSlot) Reset()         { *m = GetTownSlot{} }
func (m *GetTownSlot) String() string { return proto.CompactTextString(m) }
func (*GetTownSlot) ProtoMessage()    {}
func (*GetTownSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{4}
}
func (m *GetTownSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTownSlot.Unmarshal(m, b)
}
func (m *GetTownSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTownSlot.Marshal(b, m, deterministic)
}
func (dst *GetTownSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTownSlot.Merge(dst, src)
}
func (m *GetTownSlot) XXX_Size() int {
	return xxx_messageInfo_GetTownSlot.Size(m)
}
func (m *GetTownSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTownSlot.DiscardUnknown(m)
}

var xxx_messageInfo_GetTownSlot proto.InternalMessageInfo

func (m *GetTownSlot) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetTownSlot) GetTownCode() string {
	if m != nil {
		return m.TownCode
	}
	return ""
}

type GetAllTownSlot struct {
	TownCode             string   `protobuf:"bytes,1,opt,name=town_code,json=townCode,proto3" json:"town_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllTownSlot) Reset()         { *m = GetAllTownSlot{} }
func (m *GetAllTownSlot) String() string { return proto.CompactTextString(m) }
func (*GetAllTownSlot) ProtoMessage()    {}
func (*GetAllTownSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{5}
}
func (m *GetAllTownSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllTownSlot.Unmarshal(m, b)
}
func (m *GetAllTownSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllTownSlot.Marshal(b, m, deterministic)
}
func (dst *GetAllTownSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllTownSlot.Merge(dst, src)
}
func (m *GetAllTownSlot) XXX_Size() int {
	return xxx_messageInfo_GetAllTownSlot.Size(m)
}
func (m *GetAllTownSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllTownSlot.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllTownSlot proto.InternalMessageInfo

func (m *GetAllTownSlot) GetTownCode() string {
	if m != nil {
		return m.TownCode
	}
	return ""
}

type TownSlot struct {
	TownCode             string   `protobuf:"bytes,1,opt,name=town_code,json=townCode,proto3" json:"town_code,omitempty"`
	TownName             string   `protobuf:"bytes,2,opt,name=town_name,json=townName,proto3" json:"town_name,omitempty"`
	TownSlot             int64    `protobuf:"varint,3,opt,name=town_slot,json=townSlot,proto3" json:"town_slot,omitempty"`
	TypeId               string   `protobuf:"bytes,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName             string   `protobuf:"bytes,5,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TownSlotId           string   `protobuf:"bytes,6,opt,name=town_slot_id,json=townSlotId,proto3" json:"town_slot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TownSlot) Reset()         { *m = TownSlot{} }
func (m *TownSlot) String() string { return proto.CompactTextString(m) }
func (*TownSlot) ProtoMessage()    {}
func (*TownSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{6}
}
func (m *TownSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TownSlot.Unmarshal(m, b)
}
func (m *TownSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TownSlot.Marshal(b, m, deterministic)
}
func (dst *TownSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TownSlot.Merge(dst, src)
}
func (m *TownSlot) XXX_Size() int {
	return xxx_messageInfo_TownSlot.Size(m)
}
func (m *TownSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_TownSlot.DiscardUnknown(m)
}

var xxx_messageInfo_TownSlot proto.InternalMessageInfo

func (m *TownSlot) GetTownCode() string {
	if m != nil {
		return m.TownCode
	}
	return ""
}

func (m *TownSlot) GetTownName() string {
	if m != nil {
		return m.TownName
	}
	return ""
}

func (m *TownSlot) GetTownSlot() int64 {
	if m != nil {
		return m.TownSlot
	}
	return 0
}

func (m *TownSlot) GetTypeId() string {
	if m != nil {
		return m.TypeId
	}
	return ""
}

func (m *TownSlot) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *TownSlot) GetTownSlotId() string {
	if m != nil {
		return m.TownSlotId
	}
	return ""
}

type TownSlotList struct {
	List                 []*TownSlot `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TownSlotList) Reset()         { *m = TownSlotList{} }
func (m *TownSlotList) String() string { return proto.CompactTextString(m) }
func (*TownSlotList) ProtoMessage()    {}
func (*TownSlotList) Descriptor() ([]byte, []int) {
	return fileDescriptor_town_df10938d42660b6e, []int{7}
}
func (m *TownSlotList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TownSlotList.Unmarshal(m, b)
}
func (m *TownSlotList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TownSlotList.Marshal(b, m, deterministic)
}
func (dst *TownSlotList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TownSlotList.Merge(dst, src)
}
func (m *TownSlotList) XXX_Size() int {
	return xxx_messageInfo_TownSlotList.Size(m)
}
func (m *TownSlotList) XXX_DiscardUnknown() {
	xxx_messageInfo_TownSlotList.DiscardUnknown(m)
}

var xxx_messageInfo_TownSlotList proto.InternalMessageInfo

func (m *TownSlotList) GetList() []*TownSlot {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Town)(nil), "grpc.Town")
	proto.RegisterType((*TownList)(nil), "grpc.TownList")
	proto.RegisterType((*GetTown)(nil), "grpc.GetTown")
	proto.RegisterType((*Empty)(nil), "grpc.Empty")
	proto.RegisterType((*GetTownSlot)(nil), "grpc.GetTownSlot")
	proto.RegisterType((*GetAllTownSlot)(nil), "grpc.GetAllTownSlot")
	proto.RegisterType((*TownSlot)(nil), "grpc.TownSlot")
	proto.RegisterType((*TownSlotList)(nil), "grpc.TownSlotList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TownsClient is the client API for Towns service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TownsClient interface {
	GetTownByCode(ctx context.Context, in *GetTown, opts ...grpc.CallOption) (*Town, error)
	GetAllTown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TownList, error)
	GetTownSlotByType(ctx context.Context, in *GetTownSlot, opts ...grpc.CallOption) (*TownSlot, error)
	GetAllTownSlotByType(ctx context.Context, in *GetAllTownSlot, opts ...grpc.CallOption) (*TownSlotList, error)
}

type townsClient struct {
	cc *grpc.ClientConn
}

func NewTownsClient(cc *grpc.ClientConn) TownsClient {
	return &townsClient{cc}
}

func (c *townsClient) GetTownByCode(ctx context.Context, in *GetTown, opts ...grpc.CallOption) (*Town, error) {
	out := new(Town)
	err := c.cc.Invoke(ctx, "/grpc.Towns/GetTownByCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *townsClient) GetAllTown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TownList, error) {
	out := new(TownList)
	err := c.cc.Invoke(ctx, "/grpc.Towns/GetAllTown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *townsClient) GetTownSlotByType(ctx context.Context, in *GetTownSlot, opts ...grpc.CallOption) (*TownSlot, error) {
	out := new(TownSlot)
	err := c.cc.Invoke(ctx, "/grpc.Towns/GetTownSlotByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *townsClient) GetAllTownSlotByType(ctx context.Context, in *GetAllTownSlot, opts ...grpc.CallOption) (*TownSlotList, error) {
	out := new(TownSlotList)
	err := c.cc.Invoke(ctx, "/grpc.Towns/GetAllTownSlotByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TownsServer is the server API for Towns service.
type TownsServer interface {
	GetTownByCode(context.Context, *GetTown) (*Town, error)
	GetAllTown(context.Context, *Empty) (*TownList, error)
	GetTownSlotByType(context.Context, *GetTownSlot) (*TownSlot, error)
	GetAllTownSlotByType(context.Context, *GetAllTownSlot) (*TownSlotList, error)
}

func RegisterTownsServer(s *grpc.Server, srv TownsServer) {
	s.RegisterService(&_Towns_serviceDesc, srv)
}

func _Towns_GetTownByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TownsServer).GetTownByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Towns/GetTownByCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TownsServer).GetTownByCode(ctx, req.(*GetTown))
	}
	return interceptor(ctx, in, info, handler)
}

func _Towns_GetAllTown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TownsServer).GetAllTown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Towns/GetAllTown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TownsServer).GetAllTown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Towns_GetTownSlotByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTownSlot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TownsServer).GetTownSlotByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Towns/GetTownSlotByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TownsServer).GetTownSlotByType(ctx, req.(*GetTownSlot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Towns_GetAllTownSlotByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTownSlot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TownsServer).GetAllTownSlotByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Towns/GetAllTownSlotByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TownsServer).GetAllTownSlotByType(ctx, req.(*GetAllTownSlot))
	}
	return interceptor(ctx, in, info, handler)
}

var _Towns_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Towns",
	HandlerType: (*TownsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTownByCode",
			Handler:    _Towns_GetTownByCode_Handler,
		},
		{
			MethodName: "GetAllTown",
			Handler:    _Towns_GetAllTown_Handler,
		},
		{
			MethodName: "GetTownSlotByType",
			Handler:    _Towns_GetTownSlotByType_Handler,
		},
		{
			MethodName: "GetAllTownSlotByType",
			Handler:    _Towns_GetAllTownSlotByType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "town.proto",
}

func init() { proto.RegisterFile("town.proto", fileDescriptor_town_df10938d42660b6e) }

var fileDescriptor_town_df10938d42660b6e = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xc2, 0x40,
	0x10, 0xc6, 0x4d, 0x4c, 0xfc, 0x33, 0xfe, 0x01, 0x17, 0xa1, 0x21, 0xbd, 0x84, 0x3d, 0x14, 0xa1,
	0xd6, 0x83, 0xbd, 0xf4, 0x54, 0xa8, 0xa5, 0x88, 0x50, 0x4a, 0xb1, 0xde, 0xc5, 0x9a, 0xa5, 0x04,
	0xa2, 0x1b, 0xcc, 0x82, 0xe4, 0xd1, 0xfa, 0x36, 0x7d, 0x94, 0x32, 0xb3, 0x6b, 0xcc, 0xf6, 0x60,
	0x6f, 0x3a, 0xbf, 0xf9, 0xbe, 0x99, 0x9d, 0x2f, 0x00, 0x4a, 0x1e, 0xf7, 0x93, 0xec, 0x20, 0x95,
	0x64, 0xde, 0xd7, 0x21, 0xdb, 0xf2, 0x77, 0xf0, 0x56, 0xf2, 0xb8, 0x67, 0x7d, 0x70, 0x93, 0x38,
	0x70, 0x22, 0x67, 0xd4, 0x5e, 0xba, 0x49, 0xcc, 0xae, 0xa1, 0x8d, 0xbd, 0xeb, 0xad, 0x8c, 0x45,
	0xe0, 0x52, 0xb9, 0x85, 0x85, 0x67, 0x19, 0x8b, 0x12, 0xee, 0x37, 0x3b, 0x11, 0xd4, 0xcf, 0xf0,
	0x6d, 0xb3, 0x13, 0x7c, 0x0c, 0x2d, 0x74, 0x7c, 0x4d, 0x72, 0xc5, 0x22, 0xf0, 0xd3, 0x24, 0x57,
	0x79, 0xe0, 0x44, 0xf5, 0x51, 0x67, 0x0a, 0x13, 0x9c, 0x39, 0x41, 0xbc, 0xd4, 0x80, 0xdf, 0x40,
	0x73, 0x2e, 0x14, 0xad, 0x60, 0x8d, 0x74, 0xec, 0x91, 0xbc, 0x09, 0xfe, 0xcb, 0x2e, 0x53, 0x05,
	0x7f, 0x84, 0x8e, 0x11, 0x7c, 0xa4, 0x52, 0x31, 0x06, 0x9e, 0x2a, 0xb2, 0x53, 0x3f, 0xfd, 0xbe,
	0xb8, 0x3b, 0xbf, 0x83, 0xfe, 0x5c, 0xa8, 0xa7, 0x34, 0x2d, 0x2d, 0x2e, 0xce, 0xfd, 0x76, 0xf4,
	0x73, 0xfe, 0xed, 0xb4, 0x8f, 0xe2, 0xda, 0x47, 0x29, 0x61, 0x9e, 0x4a, 0x45, 0x17, 0xab, 0x6b,
	0x48, 0xb6, 0x57, 0xd0, 0xc4, 0xbd, 0xd7, 0x49, 0x1c, 0x78, 0xa4, 0x6b, 0xe0, 0xdf, 0x85, 0x0e,
	0x01, 0x01, 0x59, 0xfa, 0xc6, 0xb2, 0xc8, 0x04, 0x59, 0x46, 0xd0, 0x2d, 0x2d, 0x51, 0xda, 0x20,
	0x0e, 0x27, 0xd7, 0x45, 0xcc, 0xa7, 0xd0, 0x3d, 0xad, 0x4e, 0x69, 0x70, 0xf0, 0xf0, 0xe8, 0x26,
	0x8c, 0xfe, 0x39, 0x0c, 0xec, 0x58, 0x12, 0x9b, 0xfe, 0x38, 0xe0, 0x63, 0x29, 0x67, 0x63, 0xe8,
	0x99, 0x43, 0xcf, 0x0a, 0x7a, 0x60, 0x4f, 0x0b, 0x4c, 0x31, 0xac, 0x84, 0xc9, 0x6b, 0xec, 0x16,
	0xe0, 0x7c, 0x56, 0xd6, 0xd1, 0x8c, 0x12, 0x0b, 0x2b, 0x83, 0x70, 0x0d, 0x5e, 0x63, 0x0f, 0x30,
	0xa8, 0x64, 0x38, 0x2b, 0x56, 0x98, 0xda, 0xc0, 0xb2, 0x47, 0x10, 0xfe, 0x59, 0x91, 0xd7, 0xd8,
	0x0c, 0x86, 0x76, 0x7a, 0x46, 0x3c, 0x2c, 0xc5, 0x15, 0x16, 0x32, 0x5b, 0xaf, 0xa7, 0x7f, 0x36,
	0xe8, 0xfb, 0xbf, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xff, 0xcd, 0x2e, 0xcd, 0x0d, 0x03, 0x00,
	0x00,
}
