// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeName             string   `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_5f727c27914ad6de, []int{0}
}
func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (dst *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(dst, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Type) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

type TypeList struct {
	List                 []*Type  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeList) Reset()         { *m = TypeList{} }
func (m *TypeList) String() string { return proto.CompactTextString(m) }
func (*TypeList) ProtoMessage()    {}
func (*TypeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_5f727c27914ad6de, []int{1}
}
func (m *TypeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeList.Unmarshal(m, b)
}
func (m *TypeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeList.Marshal(b, m, deterministic)
}
func (dst *TypeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeList.Merge(dst, src)
}
func (m *TypeList) XXX_Size() int {
	return xxx_messageInfo_TypeList.Size(m)
}
func (m *TypeList) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeList.DiscardUnknown(m)
}

var xxx_messageInfo_TypeList proto.InternalMessageInfo

func (m *TypeList) GetList() []*Type {
	if m != nil {
		return m.List
	}
	return nil
}

type EmptyType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyType) Reset()         { *m = EmptyType{} }
func (m *EmptyType) String() string { return proto.CompactTextString(m) }
func (*EmptyType) ProtoMessage()    {}
func (*EmptyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_5f727c27914ad6de, []int{2}
}
func (m *EmptyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyType.Unmarshal(m, b)
}
func (m *EmptyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyType.Marshal(b, m, deterministic)
}
func (dst *EmptyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyType.Merge(dst, src)
}
func (m *EmptyType) XXX_Size() int {
	return xxx_messageInfo_EmptyType.Size(m)
}
func (m *EmptyType) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyType.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyType proto.InternalMessageInfo

type TypesAddRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypesAddRequest) Reset()         { *m = TypesAddRequest{} }
func (m *TypesAddRequest) String() string { return proto.CompactTextString(m) }
func (*TypesAddRequest) ProtoMessage()    {}
func (*TypesAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_5f727c27914ad6de, []int{3}
}
func (m *TypesAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypesAddRequest.Unmarshal(m, b)
}
func (m *TypesAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypesAddRequest.Marshal(b, m, deterministic)
}
func (dst *TypesAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypesAddRequest.Merge(dst, src)
}
func (m *TypesAddRequest) XXX_Size() int {
	return xxx_messageInfo_TypesAddRequest.Size(m)
}
func (m *TypesAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TypesAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TypesAddRequest proto.InternalMessageInfo

func (m *TypesAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TypesAddRequestList struct {
	Towns                []*TypesAddRequest `protobuf:"bytes,1,rep,name=towns,proto3" json:"towns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TypesAddRequestList) Reset()         { *m = TypesAddRequestList{} }
func (m *TypesAddRequestList) String() string { return proto.CompactTextString(m) }
func (*TypesAddRequestList) ProtoMessage()    {}
func (*TypesAddRequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_type_5f727c27914ad6de, []int{4}
}
func (m *TypesAddRequestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypesAddRequestList.Unmarshal(m, b)
}
func (m *TypesAddRequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypesAddRequestList.Marshal(b, m, deterministic)
}
func (dst *TypesAddRequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypesAddRequestList.Merge(dst, src)
}
func (m *TypesAddRequestList) XXX_Size() int {
	return xxx_messageInfo_TypesAddRequestList.Size(m)
}
func (m *TypesAddRequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_TypesAddRequestList.DiscardUnknown(m)
}

var xxx_messageInfo_TypesAddRequestList proto.InternalMessageInfo

func (m *TypesAddRequestList) GetTowns() []*TypesAddRequest {
	if m != nil {
		return m.Towns
	}
	return nil
}

func init() {
	proto.RegisterType((*Type)(nil), "grpc.Type")
	proto.RegisterType((*TypeList)(nil), "grpc.TypeList")
	proto.RegisterType((*EmptyType)(nil), "grpc.EmptyType")
	proto.RegisterType((*TypesAddRequest)(nil), "grpc.TypesAddRequest")
	proto.RegisterType((*TypesAddRequestList)(nil), "grpc.TypesAddRequestList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TypesClient is the client API for Types service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TypesClient interface {
	GetAllType(ctx context.Context, in *EmptyType, opts ...grpc.CallOption) (*TypeList, error)
	BulkAddType(ctx context.Context, in *TypesAddRequestList, opts ...grpc.CallOption) (*EmptyType, error)
}

type typesClient struct {
	cc *grpc.ClientConn
}

func NewTypesClient(cc *grpc.ClientConn) TypesClient {
	return &typesClient{cc}
}

func (c *typesClient) GetAllType(ctx context.Context, in *EmptyType, opts ...grpc.CallOption) (*TypeList, error) {
	out := new(TypeList)
	err := c.cc.Invoke(ctx, "/grpc.Types/GetAllType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typesClient) BulkAddType(ctx context.Context, in *TypesAddRequestList, opts ...grpc.CallOption) (*EmptyType, error) {
	out := new(EmptyType)
	err := c.cc.Invoke(ctx, "/grpc.Types/BulkAddType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypesServer is the server API for Types service.
type TypesServer interface {
	GetAllType(context.Context, *EmptyType) (*TypeList, error)
	BulkAddType(context.Context, *TypesAddRequestList) (*EmptyType, error)
}

func RegisterTypesServer(s *grpc.Server, srv TypesServer) {
	s.RegisterService(&_Types_serviceDesc, srv)
}

func _Types_GetAllType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServer).GetAllType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Types/GetAllType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServer).GetAllType(ctx, req.(*EmptyType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Types_BulkAddType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypesAddRequestList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServer).BulkAddType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Types/BulkAddType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServer).BulkAddType(ctx, req.(*TypesAddRequestList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Types_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Types",
	HandlerType: (*TypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllType",
			Handler:    _Types_GetAllType_Handler,
		},
		{
			MethodName: "BulkAddType",
			Handler:    _Types_BulkAddType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "type.proto",
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_type_5f727c27914ad6de) }

var fileDescriptor_type_5f727c27914ad6de = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x98, 0x4a, 0xf3, 0x02, 0x2d, 0xac, 0x08, 0xb1, 0x82, 0x94, 0x05, 0xa1, 0x28,
	0x44, 0x68, 0x8f, 0x9e, 0x52, 0x10, 0x2f, 0xe2, 0x21, 0x78, 0x97, 0xea, 0x2e, 0x12, 0x4c, 0x9a,
	0xb5, 0x3b, 0x41, 0xf2, 0xef, 0x65, 0x26, 0x62, 0x25, 0xf4, 0xb4, 0xcb, 0x9b, 0xf7, 0xde, 0xb7,
	0x3b, 0x00, 0x75, 0xce, 0x66, 0x6e, 0xdf, 0x50, 0xa3, 0xa2, 0x8f, 0xbd, 0x7b, 0xd7, 0x6b, 0x44,
	0x2f, 0x9d, 0xb3, 0x6a, 0x8a, 0xb0, 0x34, 0x69, 0xb0, 0x08, 0x96, 0x71, 0x11, 0x96, 0x46, 0x5d,
	0x22, 0x66, 0xef, 0xeb, 0x6e, 0x5b, 0xdb, 0x34, 0x14, 0x79, 0xc2, 0xc2, 0xf3, 0xb6, 0xb6, 0xfa,
	0x06, 0x13, 0x0e, 0x3d, 0x95, 0x9e, 0xd4, 0x15, 0xa2, 0xaa, 0xf4, 0x94, 0x06, 0x8b, 0x93, 0x65,
	0xb2, 0x42, 0xc6, 0xad, 0x19, 0x4f, 0x0b, 0xd1, 0x75, 0x82, 0xf8, 0xa1, 0x76, 0xd4, 0xb1, 0xa4,
	0xaf, 0x31, 0xe3, 0xd3, 0xe7, 0xc6, 0x14, 0xf6, 0xab, 0xb5, 0x9e, 0x94, 0x42, 0x24, 0x8c, 0x1e,
	0x2d, 0x77, 0xbd, 0xc1, 0xd9, 0xc0, 0x26, 0xa8, 0x5b, 0x8c, 0xa9, 0xf9, 0xde, 0xf9, 0x5f, 0xd6,
	0xf9, 0x81, 0xf5, 0xcf, 0x59, 0xf4, 0x9e, 0x55, 0x8b, 0xb1, 0x4c, 0xd4, 0x1d, 0xf0, 0x68, 0x29,
	0xaf, 0x2a, 0xf9, 0xe7, 0xac, 0x0f, 0xfd, 0x3d, 0x69, 0x3e, 0x3d, 0xb4, 0x30, 0x44, 0x8f, 0xd4,
	0x3d, 0x92, 0x4d, 0x5b, 0x7d, 0xe6, 0xc6, 0x48, 0xe2, 0xe2, 0x28, 0x86, 0xbd, 0xf3, 0x61, 0x99,
	0x1e, 0xbd, 0x9d, 0xca, 0x72, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0x41, 0xea, 0x47,
	0x6a, 0x01, 0x00, 0x00,
}
